### ISSUE TITLE
many of the spawn-reasons seems to have stopped working after 1.12

### ISSUE THREAD

**Issue by erik1988** [SblockCo/ChunkSpawnerLimiter#3]
EGG and SPAWNER_EGG used to work (it might be more). seems like the active-inspections are still working tho. 

I also tired using the default config and the problem still persists.

Using paper 1.12

**Comment by Jikoo** [comment]
Could be due to changes in 1.12. I was planning on catching up on issues this weekend, but apparently I'm working. RIP, will try to make time to check it out midweek if I can.

**Comment by xCykrix** [comment]
Smidgen of a necro post, but any ETA on updating this fork? 1.14.4 has introduced some horrific spawning mechanics that let thousands of entities build in in small locations.

**Comment by Jikoo** [comment]
You should be able to manually include entity types, but I'll put it on my list.

**Comment by Jikoo** [comment]
Updated spawn-reasons list for 1.14, [4.0.0](https://github.com/Jikoo/ChunkSpawnerLimiter/releases/tag/4.0.0)
