### ISSUE TITLE
paid feature request!

### ISSUE THREAD

**Issue by rby-blackruby** [SblockCo/ChunkSpawnerLimiter#6]
Hello, im not sure how often you check your emails therefor i need to contact you here.

The plugin works amazingly, but unfortunately kills mob farms.

Please add a feature asap where when a mob count is above the limit in a chunk
- no more mobs spawn in that chunk
_or_
- prioritize new spawned mobs for deletion instead of prioritizing older mobs. 

This would help mob farm a lot. Thank you.

**Feel free to send me your PayPal.**

**Comment by Jikoo** [comment]
Already exists. Use option `properties.prevent-creature-spawns`

I accept offers of money after the fact (free money is free money, what the heck), but I don't do requests where money is offered beforehand - programming is a hobby, not a job, and I'd like to keep it that way.

**Comment by rby-blackruby** [comment]
I do not see any options called prevent-creature-spawns in config.yml :(

**Comment by Jikoo** [comment]
https://github.com/Jikoo/ChunkSpawnerLimiter/blob/master/src/main/resources/config.yml#L15-L16
